apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: product-catalog-app
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: admin
  MYSQL_DATABASE: productDB
  MYSQL_USER: root
  MYSQL_PASSWORD: admin